Encerrar issues abertas por inatividade
androiddevbr/vagas pull request #2134
Opened 2022-11-09 18:09 UTC by guibranco

Cria uma action para fechar as issues que estão abertas a mais de 60 dias sem atualizações.
Isso ajuda a manter as vagas ativas e atualizadas.
Existem issues abertas desde Janeiro 2021 como #1547

2022-11-09 18:15 UTC, davidtcdeveloper commented on .github/workflow/stale-issue.yml
> +        days-before-close: 5
O que acham de colocar 30 dias aqui? Assim a vaga vai ficar aberta por 90 dias no máximo, correto?

2022-11-09 18:15 UTC, davidtcdeveloper commented
Ótima sugestão @guibranco, obrigado por preparar este PR.
Adicionei apenas uma sugestão rápida.

2022-11-09 18:33 UTC, guibranco commented on .github/workflow/stale-issue.yml
> +        days-before-close: 5
Pode ser, vou editar

2022-11-09 19:41 UTC, davidtcdeveloper commented on .github/workflow/stale-issue.yml
> +        days-before-close: 5
Show, obrigado pela sugestão. Vamos segurar o PR aberto um pouco porque ele provavelmente vai inundar o canal com mensagens de issues fechadas da primeira vez que rodar.
Vou mandar um aviso no canal para não surpreender ninguém.

2022-11-10 06:06 UTC, guibranco commented on .github/workflow/stale-issue.yml
> +        days-before-close: 5
Ele tem um limite de 30 execuções por vez, como ele roda 1x por dia, só vai atuar em 30 issues por dia. 
Se preferir posso tirar o comentário que ele adiciona, e depois que já estiver normalizado, colocamos o comentário de novo em uma nova PR, o que prefere ?

2022-11-10 11:46 UTC, walmyrcarvalho commented
Ótimo PR, obrigado pela contribuição @guibranco! 🙏

2022-11-10 11:46 UTC, walmyrcarvalho approved these changes

2022-11-10 12:52 UTC, davidtcdeveloper commented on .github/workflow/stale-issue.yml
> +        days-before-close: 5
Acho que podemos começar assim e deixar rodar por um tempo. Depois reavaliamos mudar isso ou não.

2022-11-11 19:45 UTC, merged

2024-09-26 05:12 UTC, Hugosun3434 requested changes
请求更改